config/routes.rb
BlogApp::Application.routes.draw do
  root "posts#index"
  get "comments/create"
  get "comments/destroy"
  
  resources :category do
	resources :posts
  end
  
  resources :sessions, only: [:new, :create, :destroy]
  
  match '/admin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'get'
  
  resources :posts do
	resources :comments
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :posts
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :post
	
	validates :user_name, presence: true, length: { maximum: 50, too_long: "%{count} jest maksymalnie dozwolone."}
	validates :text, presence: true
	validates_associated :post
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :category
	has_many :comments
	
	validates :tittle, presence: true, length: { maximum: 50, too_long: "%{count} jest maksymalnie dozwolone."}
	validates :text, presence: true
	validates_associated :category
end

app/models/user.rb
class User < ActiveRecord::Base
	validates :name,  presence: true, length: { maximum: 50 }, uniqueness: true
	
	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_filter :load_session_manager
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery 
  
  include SessionsHelper
  
  private
  def load_session_manager(manager = SessionManager.new(session))
    @session_manager ||= manager
  end
end

app/controllers/category_controller.rb
class CategoryController < ApplicationController
  # GET /category/1
  def show
    @posts = Post.find :all, :conditions => ["category_id = ?", params[:id]]
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :admin_only!, only: [:destroy]

  def create
	@post = Post.find(params[:post_id])
	@comment = @post.comments.build(params[:comment].permit!)
	@comment.save
	
	redirect_to @post
  end

  def destroy
	@comment = Comment.find(params[:id])
	@comment.destroy
	
	redirect_to @comment.post
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :admin_only!, only: [:new, :create, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        redirect_to @post
      else
        render action: 'new'
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        redirect_to @post
      else
        render action: 'edit'
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:tittle, :text, :category_id)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
  
    begin
      @session_manager.sign_in(params[:session][:name], params[:session][:password])
	rescue StandardError
      render 'new'
	  return
    end

	redirect_to root_path
  end

  def destroy
    @session_manager.logout
    redirect_to root_url
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  def admin_only!
    if !@session_manager.signed_in?
	   redirect_to root_path
	end
  end
  
end

app/views/category/show.html.erb
<% @posts.each do |post| %>	
  <div class="center">
    <h1> <%= link_to post.tittle, post %> </h1>
	<div style="text-align:left;">
		<%= truncate post.text, length: 180%>
	</div>
	<postFooter>
	  <div id="wrap">
	   <div class="left"><%= post.created_at %> <%= link_to post.category.name,  post.category %></div>
	   <div class="right">[<%= post.comments.count %> Komentarzy]</div>

	   <div class="clearBoth"></div>
	  </div>
	</postFooter>
  </div>
<% end %>

<% if @session_manager.signed_in? %>
<p>
	<%= link_to "Nowy post", new_post_path %>
</p>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Blog by Marek Sadowski
  </small>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "BLOG", root_path, id: "logo" %>
	  <% if @session_manager.signed_in? %>
	     <ul class="nav pull-left">
			<li><%= link_to "Wyloguj", signout_path%></li>
		 </ul>
	  <% end %>
      <nav>
	    <% Category.all.each do |category| %>	
		  <ul class="nav pull-right">
			<li><%= link_to category.name, category%></li>
		  </ul>
		<% end %>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BLOG</title>  
    <%= stylesheet_link_tag "application", media: "all", 
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<div class="center">
	<%= form_for(@post) do |f| %>
	  <% if @post.errors.any? %>
		<div id="error_explanation">
		  <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

		  <ul>
		  <% @post.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		  <% end %>
		  </ul>
		</div>
	  <% end %>

	  <div class="field">
		<%= f.label :Tytul %>
		<%= f.text_field :tittle %>
	  </div>
	  <div class="field">
		<%= f.label :Tekst %>
		<%= f.text_area :text %>
	  </div>
	  <div class="field">
		<%= f.label :Kategoria %>
		<%= f.select :category_id, options_from_collection_for_select(Category.all, :id, :name) %>
		</div>
	  <div class="actions">
		<%= f.submit %>
	  </div>
	<% end %>
</div>

app/views/posts/edit.html.erb
<h1>Edycja posta</h1>

<%= render 'form' %>

<%= link_to 'Pokaż', @post %> |
<%= link_to 'Wróć', posts_path %>

app/views/posts/index.html.erb
<% @posts.each do |post| %>	
  <div class="center">
    <h1> <%= link_to post.tittle, post %> </h1>
	<div style="text-align:left;">
		<%= truncate post.text, length: 180%>
	</div>
	<postFooter>
	  <div id="wrap">
	   <div class="left"><%= post.created_at %> <%= link_to post.category.name,  post.category %></div>
	   <div class="right">[<%= post.comments.count %> Komentarzy]</div>

	   <div class="clearBoth"></div>
	  </div>
	</postFooter>
  </div>
<% end %>

<% if @session_manager.signed_in? %>
<p>
	<%= link_to "Nowy post", new_post_path %>
</p>
<% end %>

app/views/posts/new.html.erb
<h1>Nowy post</h1>

<%= render 'form' %>

<%= link_to 'Wróć', posts_path %>

app/views/posts/show.html.erb
<div class="center">
    <h1> <%= @post.tittle %> </h1>
	<div style="text-align:left;">
		<%= @post.text %>
	</div>
   <postFooter><div><%= @post.created_at %> <%= link_to @post.category.name,  @post.category %></div></postFooter>
</div>
<div>
   <p>Komentarze(<%= @post.comments.count %>): </p>	
   <% @post.comments.each do |comment| %>
    <div class="comment">
		<header><%= comment.user_name %> (<%= comment.created_at %>)</header>
		<div><%= comment.text %></div>
	</div>
	<% if @session_manager.signed_in? %>
	   <%= link_to "Usuń", [@post, comment], :method => :delete, :confirm => "Czy jesteś pewny, że chcesz usunąć ten komentarz?" %>
	<% end %>
	<% end %>
   
    <div class="center">
		<%= form_for [@post, @post.comments.build] do |f| %>
		  <div class="field">
			<%= f.label :"Komentarz:" %>
			<%= f.text_area :text%>
		  </div>
		  <div class="field">
			<%= f.label :"Użytkownik:" %>
			<%= f.text_field :user_name%>
		  </div>
		  <div class="actions">
			<%= f.submit "Post comment" %>
		  </div>
		<% end %>
    </div>
	<%= link_to "Wróć", posts_path %>
	<% if @session_manager.signed_in? %>
		|
		<%= link_to "Edytuj", edit_post_path(@post) %>
		|
		<%= link_to "Usuń", @post, :method => :delete, :confirm => "Czy jesteś pewny, że chcesz usunąć ten post?" %>
	<% end %>
</div>

	